src/Entity/Videos.php
<?php

namespace App\Entity;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideosRepository")
 */
class Videos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=700)
     */
    private $link;

    public function getId()
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getVideoId()
    {
        $link = explode('=', $this->link);
        return array_pop($link);
    }

}

templates/article.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ article.title }} {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="show-article-container p-3 mt-4">
                <div class="row">
                    <div class="col-sm-12">
                        <img class="show-article-img" src="{{ asset('images/article.jpg') }}">
                        <div class="show-article-title-container d-inline-block pl-3 align-middle">
                            <span class="show-article-title ">{{ article.title }}</span>
                            <br>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="article-text">
                            {{ article.content }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html.twig
<!doctype html>
<html lang="en">

<head>
    <title>{% block title %}Welcome to the WildSite{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
              integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('css/font-awesome.css') }}">
        <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
        <link rel="stylesheet" href="{{ asset('css/formstyles.css') }}">
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark navbar-bg mb-5">
    <a style="margin-left: 75px;" class="navbar-brand space-brand" href="{{ path('app_homepage') }}">The WildSite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a style="color: #fff;" class="nav-link" href="{{ path('app_tour_page') }}">Даты концертов</a>
            </li>
            <li class="nav-item">
                <a style="color: #fff;" class="nav-link" href="{{ path('app_videos_page') }}">Клипы Wildways</a>
            </li>

            {% if not(app.user) %}
                <li class="nav-item">
                    <a style="color: #fff;" class="nav-link" href="{{ path('register') }}">Зарегестрироваться</a>
                </li>
                <li class="nav-item">
                    <a style="color: #fff;" class="nav-link" href="{{ path('login') }}">Войти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a style="color: #fff;" class="nav-link" href="{{ path('logout') }}">Выйти</a>
                </li>
            {% endif %}
        </ul>
        {#<form class="form-inline my-2 my-lg-0">#}
        {#<input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search">#}
        {#<button class="btn btn-info my-2 my-sm-0" type="submit">Поиск</button>#}
        {#</form>#}
        {#<ul class="navbar-nav ml-auto">#}
        {#<li class="nav-item dropdown" style="margin-right: 75px;">#}
        {#<a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
        {#<img class="nav-profile-img rounded-circle" src="images/268x0w.jpg">#}
        {#</a>#}
        {#<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">#}
        {#<a class="dropdown-item" href="#">Profile</a>#}
        {#<a class="dropdown-item" href="#">Create Post</a>#}
        {#<a class="dropdown-item" href="#">Logout</a>#}
        {#</div>#}
        {#</li>#}
        {#</ul>#}
    </div>
</nav>

{% block body %}{% endblock %}

<footer class="footer">
    <div class="container text-center">
        <span class="text-muted">Made with PAIN by <a href="https://vk.com/spasm_page">SPASM</a></span>
    </div>
</footer>

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
            integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
            crossorigin="anonymous"></script>
    <script>
        $('.dropdown-toggle').dropdown();
    </script>
{% endblock %}
</body>
</html>

templates/error404.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Page NOT FOUND</h1>
{% endblock %}

templates/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="margin-home">
        <div class="container">
            <h1>Список новостей</h1>
            <div class="row">
                <!-- Article List -->
                <div class="col-sm-12 col-md-8">
                    <!-- H1 Article -->
                    {#<a class="main-article-link" href="#">#}
                    {#<div class="main-article mb-5 pb-3">#}
                    {#<img src="{{ asset('images/meteor-shower.jpg') }}" alt="meteor shower">#}
                    {#<h1 class="text-center mt-2">Ursid Meteor Shower: <br>Healthier than a regular shower?</h1>#}
                    {#</div>#}
                    {#</a>#}
                    <!-- Supporting Articles -->
                    {% for article in articles %}
                        <div class="article-container my-1">
                            <a href="{{ path('article_show', {article: article.id}) }}">
                                <img class="article-img" src="{{ asset('images/Article.jpg') }}">
                                <div class="article-title d-inline-block pl-3 align-middle">
                                    <span><b>{{ article.title }}</b></span>
                                    <br>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="navigation text-center">
        {{ knp_pagination_render(articles) }}
    </div>
{% endblock %}

templates/special_theme.html.twig
{% extends 'theme.html.twig' %}

{%- block form_widget_simple -%}
    {% set attr = attr|default({})|merge({class: 'special-class '~attr['class']|default('')}) %}
    {{ parent() }}
{%- endblock form_widget_simple -%}

templates/theme.html.twig
{% extends 'form_div_layout.html.twig' %}

{%- block form_widget_simple -%}
    {% set attr = attr|default({})|merge({class: 'some-class '~attr['class']|default('')}) %}
    {{ parent() }}
{%- endblock form_widget_simple -%}

{%- block email_widget -%}
    {% set attr = attr|default({})|merge({class: 'email-class '~attr['class']|default('')}) %}
    {{ parent() }}
{%- endblock email_widget -%}

templates/tour.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="margin-home">
        <div class="container">
            <div class="row">
                <!-- Article List -->
                <div class="col-sm-12 col-md-8">
                    <!-- H1 Article -->
                    <a class="main-article-link" href="#">
                        <div class="main-article mb-5 pb-3">
                            <img src="{{ asset('images/wildways_photo.jpg') }}" alt="meteor shower">
                            <h1 class="text-center mt-2">Wildways в твоем городе! <br>Даты концертов:</h1>
                        </div>
                    </a>
                    <!-- Supporting Articles -->
                    {% for tour in tours %}
                        <div class="article-container my-1">
                            <a href="https://wildwaystour.com">
                                <div class="article-title d-inline-block pl-3 align-middle">
                                    <div><i>{{ tour.city }}</i></div>
                                    <br>
                                </div>
                                <div class="article-title d-inline-block pl-3 align-middle">
                                    <div><b>Клуб: {{ tour.club }}</b></div>
                                    <br>
                                </div>
                                <div class="article-title d-inline-block pl-3 align-middle">
                                    <div>Дата: {{ tour.date|date('d.m///H:i') }}</div>
                                    <br>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/videos.html.twig
{% extends 'base.html.twig' %}

{% block title %} Клипы Wildways {% endblock %}

{% block body %}
    {% for video in videos %}
        <div style="position:relative;height: 0; padding-bottom:29.81%; ">
            <iframe src="https://www.youtube.com/embed/{{ video.videoId }}?ecver=2"
                    style="position: absolute;width:50%;height:100%;left:25%" width="1208" height="360" frameborder="0"
                    allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <br>
    {% endfor %}
{% endblock %}